#!/bin/bash
CMD_READLINK="readlink -f"
if [[ "$OSTYPE" == "darwin"* ]]; then
	CMD_READLINK="readlink"
SCRIPTDIR="$(cd "$(dirname $($CMD_READLINK "$0"))"; pwd)"
java -cp "$SCRIPTDIR/{{COMPILE_CLASSPATH}}" com.tameif.tame.compiler.TAMECompilerMain $@
